### ISSUE TITLE
Bookmark bar cut logos

### ISSUE THREAD

**Issue by GidonKad** [int128/bntp#10]
Hi!
Bookmark bar's icon's are cut since I installed the extension today. 

Updated chrome, happens in two of my computers 

Thank you! The extension is totally awesome

![image](https://user-images.githubusercontent.com/35837067/35439187-53f98d1e-02a2-11e8-8b14-de24b848d031.png)

**Comment by int128** [comment]
Thank you for the report. Would you tell me your Chrome version?

**Comment by woutervandiggelen** [comment]
That's because the bookmark has an empty name, in this case a "&nbsp;" should be added to the "TileFolderItem__ButtonBody" element so the full icon will show.

**Comment by int128** [comment]
Fixed since v3.0.0.
