### ISSUE TITLE
Feature Request - Search/Filter 

### ISSUE THREAD

**Issue by caddac** [int128/bntp#14]
As my list of bookmarks grows, sorting just isn't cutting it. I'm starting to look for solutions for searching my bookmarks quickly. 
Please consider adding a search/filter function. Thinking a simple search box at the top that would show only items that match the search term entered. Would you consider taking pull requests for this feature?

**Comment by BlackPhlox** [comment]
I think this project is more or less abandon. However, I was looking for something similar, so I made this. PR is gonna be up soon.

![image](https://user-images.githubusercontent.com/25123512/84509760-771a4800-acc4-11ea-9a35-9b1349d890af.png)

**Comment by int128** [comment]
Thank you for your contribution. I'm still using this extension everyday but do not maintain it for now. Pull requests are welcome. I will merge them and release a new version to Chrome Store. 

I'm planning to rebuild this project with the latest version of React, Redux and TypeScript but it may need long term.

**Comment by int128** [comment]
Bookmark search is available since v3.0.0.
