### ISSUE TITLE
Feature request: indent of sub-folder in bookmarks

### ISSUE THREAD

**Issue by gridge** [int128/bntp#6]
Hi,
 let me start saying that this is a great, simple extension that I truly love :)
In my bookmarks I have few sub-folders that I use to organize them better (as I bet most of people do). I was wondering if it could be possible to allow a sort of "indentation" to display sub-folders instead as a plain list. A "one cell" indent for each level of sub-folder would make the work. Do you think that it would be possible?
 Thanks
Simone

**Comment by dominoto** [comment]
I would like this too, with the added request that folders and subfolders expand on mouse clicking them, not show them all the time. When you have over 500 bookmarks things get a little hectic :)

**Comment by int128** [comment]
Folder indent feature has been released in 2.3.0.
Thanks for the feature request.
